### ISSUE TITLE
RuntimeSqliteColumnDefinition is not a type. 

### ISSUE THREAD

**Issue by carlos-labrador** [greenbits/brick#124]
Hi @tshedor ,

I am getting some errors after generating adapters on latest Flutter stable channel, this is a new project.

**pubspec:**
```
dependencies:
  brick_offline_first: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>= 1.10.1'
  brick_offline_first_with_rest_build:
    git:
      url: https://github.com/greenbits/brick.git
      path: packages/brick_offline_first_with_rest_build
```

```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (5 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

Thanks in advance.

**Comment by tshedor** [comment]
Hi @carlos-labrador , can you please try adding this? I'll sort those pubspec issues soon

```yaml
dependency_overrides:
  brick_sqlite:
    git:
      url: https://github.com/greenbits/brick.git
      path: packages/brick_sqlite
```
