### ISSUE TITLE
Can't create valid migrations file

### ISSUE THREAD

**Issue by polRk** [greenbits/brick#168]
I do not know what the problem is, but when you start the build, brick deletes all the columns and then creates them again

```

  brick_offline_first_with_rest_build:
    git:
      url: https://github.com/greenbits/brick.git
      path: packages/brick_offline_first_with_rest_build
  build_runner: any
```

I think that after you added null safety, I lost the generation migration mechanism
