### ISSUE TITLE
build command fails due to a syntax error in generated code

### ISSUE THREAD

**Issue by diegonc** [greenbits/brick#169]
In a new flutter project I added the dependencies on brick

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  brick_offline_first: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  brick_offline_first_with_rest_build:
    git:
      url: https://github.com/greenbits/brick.git
      path: packages/brick_offline_first_with_rest_build
  build_runner: any
```
When I run the build command ( `flutter pub run build_runner build --verbose` ) I get the following error:

```
[SEVERE] brick_offline_first_with_rest_build:brickAdaptersBuilder on lib/app/models/product_variant.dart (cached):

Could not format because the source could not be parsed:

line 2, column 56 of .: Expected to find ')'.
  ╷
2 │         return ProductVariant(id:  data['id'] as String*,
  │                                                        ^
  ╵
package:dart_style/src/dart_formatter.dart 138:7               DartFormatter.formatSource
package:dart_style/src/dart_formatter.dart 71:12               DartFormatter.format
package:brick_build/src/serdes_generator.dart 249:23           SerdesGenerator.generate
package:brick_build/src/adapter_generator.dart 54:25           AdapterGenerator.serializerFunctions.<fn>
dart:collection                                                ListMixin.fold
package:brick_build/src/adapter_generator.dart 53:23           AdapterGenerator.serializerFunctions
package:brick_build/src/adapter_generator.dart 72:8            AdapterGenerator.generate
package:brick_build/src/annotation_super_generator.dart 33:29  AnnotationSuperGenerator.generateAdapter
package:brick_build/src/builders/adapter_builder.dart 24:32    AdapterBuilder.build
```

The test project is at https://github.com/diegonc/test_brick and the entity at https://github.com/diegonc/test_brick/blob/master/lib/app/models/product_variant.dart

`flutter doctor` output is:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.5, on Linux, locale es_AR.UTF-8)
    • Flutter version 2.0.5 at /home/diegonc/dev/tools/flutter
    • Framework revision adc687823a (hace 10 días), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/diegonc/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/diegonc/dev/tools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/diegonc/dev/tools/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/diegonc/dev/tools/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```

Any idea why the syntax error is happening or how to debug it?
